export const actions = {
  ADD_TASK: 'ADD_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  CLEAR_TASK: "CLEAR_TASK",
  CLEAR_OLD_TASK: "CLEAR_OLD_TASK",
  UPDATE_NEW_TASK_TITLE: "UPDATE_NEW_TASK_TITLE",
  UPDATE_TASK_TITLE: "UPDATE_TASK_TITLE",
  UPDATE_TASK_LIST: "UPDATE_TASK_LIST",
}


